<div class="page-header"><h2>Contact Us</h2></div>

<div class="row">
<?php
$form = $this->form;
$action =  $this->url('reporting/site-pages',array('action' => 'send-message'));
$form->setAttributes(array(
	'action' => $action,
	'method' => 'POST',
));
//echo $this->form()->openTag($form);
?>
<div class="col-md-6">
	<?php echo $this->form()->render($form); ?>
</div>
<?php 
//echo $this->form()->closeTag($form);
?>
</div>