<div class="container">
	<div class="row">
		<div class="col-md-12 jumbotron">
			
			<h1>Welcome!</h1>
			<p>
				Lorem ipsum dolor. Lorem ipsum dolor. Lorem ipsum dolor.
			</p>
			<a class="btn btn-default btn-lg">Explain More</a>
			
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4 c-home-modules " >
			<h3>Dashboard</h3>
			<p class="c-home-caption">
				View scores. Generate reports. See campaign  progression. Manage my reviewers
			</p>
			<p>
				<a class="btn btn-primary"
				href="<?php echo $this->url('reporting/dashboard-interface'); ?>">Go to Dashboard</a>
				<a class="btn btn-default">More info</a>
			</p>
		</div>
		<div class="col-md-4 c-home-modules">
			<h3>Administation</h3>
			<p class="c-home-caption">
				Start campaign. Build questionnaires. Manage users and assigments
			</p>
			<p>
				<a class="btn btn-primary"
				href="<?php echo $this->url('reporting/admin-interface'); ?>">Go to Admin</a>
				<a class="btn btn-default">More info</a>
			</p>
		</div>
		<div class="col-md-4 c-home-modules">
			<h3>Web Survey</h3>
			<p class="c-home-caption">
				Are you ready to fill up the survey? It will take less than 2 minutes.
			</p>
			<p>
				<a class="btn btn-primary"
				href="<?php echo $this->url('web-survey'); ?>">Start Survey</a>
				<a class="btn btn-default">More info</a>
			</p>
		</div>
	</div>
</div>
