<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mailer\Module'                        => __DIR__ . '/Module.php',
    'Mailer\Controller\MailController' 		=> __DIR__ . '/src/Mailer/Controller/MailController.php',
    'MailerTest\Framework\TestCase'        => __DIR__ . '/tests/Mailer/Framework/TestCase.php',
    'MailerTest\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);