<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reporting\Module'                        => __DIR__ . '/Module.php',
    'Reporting\Controller\DashboardController' => __DIR__ . '/src/Reporting/Controller/DashboardController.php',
    'ReportingTest\Framework\TestCase'        => __DIR__ . '/tests/Reporting/Framework/TestCase.php',
    'ReportingTest\SampleTest'                => __DIR__ . '/tests/Reporting/SampleTest.php',
);
