<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'QuestionaireBuilder\Module'                        => __DIR__ . '/Module.php',
    'QuestionaireBuilder\Controller\BuilderController' => __DIR__ . '/src/QuestionaireBuilder/Controller/BuilderController.php',
    'QuestionaireBuilderTest\Framework\TestCase'        => __DIR__ . '/tests/QuestionaireBuilder/Framework/TestCase.php',
    'QuestionaireBuilderTest\SampleTest'                => __DIR__ . '/tests/QuestionaireBuilder/SampleTest.php',
);
