<div class="row">
	<div class="col-md-12">
		<h4>Load User List</h4>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<?php 
			$userLoaderForm = $this->userLoaderForm;
			$userLoaderForm->prepare();
			$userLoaderForm->setAttribute('method', 'POST');
			$userLoaderForm->setAttribute('action', $this->url('reporting/loader-interface',array('action' => 'load-user-list')));
			echo $this->form()->openTag($userLoaderForm);
		?>
			<div class="form-group">
				<div class="input-group">
					<?php
					echo $this->formElement($userLoaderForm->get('fileUpload')
						->setAttribute('class','form-control'))	?>
					<span class="input-group-btn"><?php echo $this->formElement($userLoaderForm->get('fileSubmit')
					->setAttribute('class','btn btn-primary')) ?>
					</span>
				</div>
			</div>
		<?php echo $this->form()->closeTag(); ?>
		</div>

</div>
<div class="row">
	<div class="col-md-12">
		<?php if (isset($this->success)) 
		{
			echo '<div class="alert alert-info">';
			foreach ($this->success as $success) {
				echo '<li>'.$success;
				echo '<strong><a href="'.$this->url('reporting/admin-interface',array('action' => 'index')).'">Click</a></strong>';
			}
			echo '</div>';
		}
		?>

			<?php if (isset($this->error)) 
		{
			echo '<div class="alert alert-danger">';
			foreach ($this->error as $error) {
				echo '<li>'.$error;
			}
			echo '</div>';
		}
		?>
	</div>
</div>
