<div class="row">
	<div class="col-md-12">
		<h4>Load User List</h4>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<?php 
			$userLoaderForm = $this->userLoaderForm;
			$userLoaderForm->prepare();
			$userLoaderForm->setAttribute('method', 'POST');
			$userLoaderForm->setAttribute('action', $this->url('reporting/loader-interface',array('action' => 'load-user-list')));
			echo $this->form()->openTag($userLoaderForm);
		?>
			<div class="form-group">
				<div class="input-group">
					<?php
					echo $this->formElement($userLoaderForm->get('fileUpload')
						->setAttribute('class','form-control'))	?>
					<span class="input-group-btn"><?php echo $this->formElement($userLoaderForm->get('fileSubmit')
					->setAttribute('class','btn btn-primary')) ?>
					</span>
				</div>
			</div>
		<?php echo $this->form()->closeTag(); ?>
		</div>

</div>
<div class="row">
	<div class="col-md-12">
		<?php if (isset($this->success)) 
		{
			echo $this->headScript()->appendFile($this->basePath() . '/js/reporting/loader/show_modal.js');
			/* echo '<div class="alert alert-info">';
			foreach ($this->success as $success) {
				echo '<li>'.$success;
				echo '<strong><a href="'.$this->url('reporting/admin-interface',array('action' => 'index')).'">Click</a></strong>';
			}
			echo '</div>'; */
		}
		?>

			<?php if (isset($this->error)) 
		{
			echo $this->headScript()->appendFile($this->basePath() . '/js/reporting/loader/show_modal.js');
			/* echo '<div class="alert alert-danger">';
			foreach ($this->error as $error) {
				echo '<li>'.$error;
			}
			echo '</div>'; */
		}
		?>
	</div>
</div>

<div class="modal fade upload-msg-log">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Upload Log
            </div>
            <div class="modal-body">
            <?php if (isset($this->success)) { ?>
            	<div class="alert alert-success">
            	<?php   foreach ($this->success as $success) {
               		echo '<li>'.$success; 
                } ?>
            	</div>
            <?php } ?>

            <?php if (isset($this->error)) { ?>
            	<div class="alert alert-danger">
            	<?php   foreach ($this->error as $error) {
               		echo '<li>'.$error; 
                } ?>
            	</div>
            <?php } ?>
            </div>
            <div class="modal-footer">
            	
            	<?php if (isset($this->success)) { ?>
            	<a class="btn btn-success" href="<?php echo $this->url('reporting/admin-interface', array('action' => 'index')); ?>">Good
            	</a>
            	<?php } ?>
            	<button class="btn btn-default" data-dismiss="modal">Try Again</button>
            </div>
        </div>
    </div>
</div>
