<div class="page-title"><h2>Load User List</h2></div>
<div class="row">
	<div class="col-md-8">
		<div class="container">
		<?php 
			$userLoaderForm = $this->userLoaderForm;
			$userLoaderForm->prepare();
			$userLoaderForm->setAttribute('method', 'POST');
			echo $this->form()->openTag($userLoaderForm);
		?>
			<div class="form-group">
				<div class="input-group">
					<?php echo $this->formElement($userLoaderForm->get('fileUpload')
						->setAttribute('class','form-control'))	?>
					<span class="input-group-btn"><?php echo $this->formElement($userLoaderForm->get('fileSubmit')
					->setAttribute('class','btn btn-primary')) ?>
					</span>
				</div>
			</div>
		<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="container">
	

		<?php if (isset($this->success)) 
		{
			echo '<div class="alert">';
			foreach ($this->success as $success) {
				echo '<li>'.$success;
			}
			echo '</div>';
		}
		?>

			<?php if (isset($this->error)) 
		{
			echo '<div class="alert alert-danger">';
			foreach ($this->error as $error) {
				echo '<li>'.$error;
			}
			echo '</div>';
		}
		?>
		</div>
	</div>
</div>
