<div class="page-header"><h2>Questionaire Builder</h2></div>
<div class="row">
    <div class="col-md-4 well">
        <h3>Step 1</h3>
        <ol>
        <li>
            What population do you want to track performance?
            <select class="form-control c-input" multiple>
                <option>SSR</option>
                <option>Logistics Manager</option>
                <option>Sales Manager</option>
                <option>Accounting</option>
            </select>
        </li>
        <li>
            What country?
            <select class="form-control c-input" multiple>
                <option>Netherlands</option>
                <option>Japan</option>
                <option>US</option>
                <option>China</option>
            </select>
        </li>
        </ol>
    </div>
    <div class="col-md-8 well">
    <h3>Step 2</h3>
        <div class="col-md-3">
            <div class="btn-group-vertical">
                <button class="btn btn-default">Lead Generation</button>
                <button class="btn btn-default">Negotiation Agreement</button>
                <button class="btn btn-default">Post Closet</button>
                <button class="btn btn-default">Account Admin</button>
                <button class="btn btn-primary">Internal Admin</button>
                <button class="btn btn-default">Sales Planning</button>
                <button class="btn btn-default">Exception Handling</button>
            </div>
        </div>
        <div class="col-md-9">
        <h4>This questions will be asked:</h4>
            <ul class="list-group">
                <li class="list-group-item"><b>Q13</b> SSR updates data in CRM on behalf of reps quickly and accurately</li>
                <li class="list-group-item"><b>Q14</b> SSR provides timely forecasts to CCAM</li>
                <li class="list-group-item"><b>Q15</b> SSR executes timely and accurate internal performance reports</li>
            </ul>
        </div>
    </div>    
</div>
<div class="row">
    <div class="col-md-12 well">
        <h3>Step 3</h3>
        Please confirm everything.<br>
        <a class="btn btn-primary btn-lg" href="<?php echo $this->url('questionaire-builder/build-interface',array('action' => 'done')) ?>">Done</a>
    </div>  
</div>

