<div class="page-header"><h2>Questionnaire Builder</h2></div>
<div class="container"><h3>Step 1</h3>
<div class="row">
	<div class="col-md-5">
		<div class="container">What population do you want to track performance?</div>
			<div class="checkbox">
				<label><input type="checkbox"> SSR</label>
			</div>
	</div>
    <div class="col-md-7 question-selectors">
        <div class="panel-group" id="questions-panel">
            <div class="panel panel-default">
                <div class="panel-heading"><span class="panel-title">
                        <a data-toggle="collapse" data-parent="#questions-panel" href="#qcat1">
                            category
                        </a>
                    </span>
                </div>
                <div class="panel-collapse collapse in" id="qcat1">
                    <div class="panel-body">
                        dsdsd
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>