<div class="page-title"><h2>Dashboard</h2></div>
<div class="row">
    <?php echo $this->filters?>
</div>
<br>
<div class="row ">
    <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <strong>*</strong> Be consious in sharing results that the sampling is sufficiently low to easily identify individual respondent's answers
    </div>
    <?php 
    foreach ($this->scoring as $score){
        echo $this->$score;
    }
    ?>
</div>
<div class="row">
    <button class="btn btn-default btn-lg"><span class="glyphicon glyphicon-download"></span> Export to Excel</button>
    <button class="btn btn-default btn-lg"><span class="glyphicon glyphicon-download"></span> Download Reports</button>
</div>