<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title">Assignment Table</span>
	</div>
	<table class="table">
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Role</th>
			<th>Country</th>
			<!--<th>Status</th>-->
			<th>Reviewers</th>
		</tr>
		<?php foreach ($this->data as $field => $subject) { ?> 
		<tr>
			<td><?php echo $subject['first_name'] ?></td>
			<td><?php echo $subject['last_name'] ?></td>
			<td><?php echo $subject['role'] ?></td>
			<td><?php echo $subject['country'] ?></td>
			<!--<td><h4>
					<span class="label label-success label-lg">Reviewers approved by Manager</span>
				</h4></td> -->
			<td>
				<div class="row">
				<?php foreach ($subject['reviewers'] as $reviewer)  { ?>
					<div class="col-md-4">
						<?php echo $reviewer['first_name'] . ' ' . $reviewer['last_name']; ?>
					</div>
				<?php } ?>
				</div>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="panel-body"></div>
	<div class="panel-footer">
				<?php echo $this->paginationSearch; ?>
			</div>
</div>
