<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title">Assignemt Table</span>
	</div>
	<table class="table">
		<tr>
			<th>Subject</th>
			<th>Status</th>
			<th>Key Task</th>
			<th>Respondents</th>
		</tr>
		<tr>
			<td>John Doe</td>
			<td><h4>
					<span class="label label-success label-lg">Reviewer approved by SSR</span>
				</h4></td>
			<td>Lead Generation</td>
			<td>
				<ul>
					<li>Marcos Mariano</li>
					<li>Jose Rizal</li>
					<li>Lelouch Lamperogue</li>
				</ul>
			</td>
		</tr>
		<tr>
			<td>Jane Daisy</td>
			<td><h4>
					<span class="label label-warning label-lg">Waiting for SSR approval</span>
				</h4></td>
			<td>Agreement Negotiation</td>
			<td>
				<ul>
					<li>Kyle Korver</li>
					<li>Bruce Chan</li>
					<li>Adolf Van Doe</li>
				</ul>
			</td>
		</tr>
		<tr>
			<td>Jane Daisy</td>
			<td><h4>
					<span class="label label-warning label-lg">Waiting for SSR approval</span>
				</h4></td>
			<td>Agreement Negotiation</td>
			<td>
				<ul>
					<li>Kyle Korver</li>
					<li>Bruce Chan</li>
					<li>Adolf Van Doe</li>
				</ul>
			</td>
		</tr>
		<tr>
			<td>Jane Daisy</td>
			<td><h4>
					<span class="label label-warning label-lg">Waiting for SSR approval</span>
				</h4></td>
			<td>Agreement Negotiation</td>
			<td>
				<ul>
					<li>Kyle Korver</li>
					<li>Bruce Chan</li>
					<li>Adolf Van Doe</li>
				</ul>
			</td>
		</tr>
		<tr>
			<td>John Doe</td>
			<td><h4>
					<span class="label label-success label-lg">Reviewer approved by SSR</span>
				</h4></td>
			<td>Lead Generation</td>
			<td>
				<ul>
					<li>Marcos Mariano</li>
					<li>Jose Rizal</li>
					<li>Lelouch Lamperogue</li>
				</ul>
			</td>
		</tr>
	</table>
	<div class="panel-body"></div>
	<div class="panel-footer">
				<?php echo $this->paginationSearch; ?>
			</div>
</div>
