<div class="row">
	<div class="col-md-2">
		<button class="btn btn-default">Download Excel</button>
	</div>
	<div class="col-md-6">
		<ul class="pagination c-pagination-footer">
			<li><a href="#">&laquo;</a></li>
			<li><a href="#" class="active">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><a href="#">4</a></li>
			<li><a href="#">5</a></li>
			<li><a href="#">&raquo;</a></li>
		</ul>
	</div>
	<div class="col-md-4">
		<div class="input-group">
			<input type="text" class="form-control input-sm"
				placeholder="Name, Key task, etc"> <span class="input-group-btn"><button
					class="btn btn-primary btn-sm">Search</button></span>
		</div>
	</div>

</div>