<div class="container">
	<div class="btn-group">
		<a href="<?php echo $this->url('reporting/admin-interface',array('action' => 'index')) ?>"
		class="btn btn-default btn-lg"><span class="glyphicon glyphicon-user"></span> User editor</a>
		<a href="<?php echo $this->url('reporting/admin-interface',array('action' => 'assignment')) ?>"
		class="btn btn-default btn-lg"><span class="glyphicon glyphicon-list-alt"></span> Assigment editor</a>
	</div>
</div>