<div class="container">
	<div class="btn-group">
		<a href="<?php echo $this->url('reporting/admin-interface',array('action' => 'index')) ?>"
		class="btn btn-default btn-lg"><span class="glyphicon glyphicon-user"></span> Employee editor</a>
		<a href="<?php echo $this->url('reporting/admin-interface',array('action' => 'assignment')) ?>"
		class="btn btn-default btn-lg"><span class="glyphicon glyphicon-list-alt"></span> Assignments</a>
		<a href="<?php echo $this->url('questionaire-builder/build-interface') ?>"
		class="btn btn-default btn-lg"><span class="glyphicon glyphicon-file"></span> Questionnaire</a>
		<a class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok"></span> Launch Survey</a>
		<a class="btn btn-warning btn-lg"><span class="glyphicon glyphicon-ok"></span> Close Campaign</a>
	</div>
</div>