<?php
			/* $userLoaderForm = $this->userLoaderForm;
			$userLoaderForm->prepare();
			//$userLoaderForm->setAttribute('action' , 'cj');
			$userLoaderForm->setAttribute('method', 'POST');
			echo $this->form()->openTag($userLoaderForm);
			$element = $userLoaderForm->get('fileUpload');
			echo $this->formLabel($element);
			echo $this->formElement($element);
			echo $this->formElementErrors($element);

			$element = $userLoaderForm->get('fileSubmit')->setAttribute('class','btn btn-default');;
			echo $this->formElement($element);
			echo $this->form()->closeTag();
			*/
		?>
<div class="panel panel-default">
	<div class="panel-heading">List of Users</div>
	<div class="panel-body">
		<button class="btn btn-default"></span> Create new user</button>
	</div>
	<table class="table">
		<tr>
			<th>User ID</th>
			<th>Email</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Country</th>
			<th>Role</th>
			<th>Action</th>
		</tr>
	<?php foreach ($this->data as $key => $user) { ?> 
		<tr>
			<td><?php echo $key ?></td>
			<td><?php echo $user['email'] ?></td>
			<td><?php echo $user['first_name'] ?></td>
			<td><?php echo $user['last_name'] ?></td>
			<td><?php echo $user['country'] ?></td>
			<td><?php echo $user['role'] ?></td>
			<td>
				<span class="btn-group">
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-trash"></span></button>
				</span>
			</td>
		</tr>
	<?php } ?>
	</table>
	<div class="panel-footer">
		<?php echo $this->paginationSearch; ?>
	</div>
</div>