<div class="panel panel-default">
	<div class="panel-heading">List of Users</div>
	<div class="panel-body">
		<button class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> New User</button>
		<button class="btn btn-default">Import List</button>
	</div>
	<table class="table">
		<tr>
			<th>Username</th>
			<th>Full Name</th>
			<th>Email</th>
			<th>Type</th>
			<th>Action</th>
		</tr>
		<tr>
			<td>John.Doe</td>
			<td>John Doe</td>
			<td>John.Doe@apl.com</td>
			<td></td>
			<td>
				<span class="btn-group">
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-trash"></span></button>
				</span>
			</td>
		</tr>
		<tr>
			<td>John.Doe</td>
			<td>John Doe</td>
			<td>John.Doe@apl.com</td>
			<td></td>
			<td>
				<span class="btn-group">
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-trash"></span></button>
				</span>
			</td>
		</tr>
		<tr>
			<td>John.Doe</td>
			<td>John Doe</td>
			<td>John.Doe@apl.com</td>
			<td></td>
			<td>
				<span class="btn-group">
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>
					<button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-trash"></span></button>
				</span>
			</td>
		</tr>
	</table>
	<div class="panel-footer">
		<?php echo $this->paginationSearch; ?>
	</div>
</div>