<div class="page-title"><h3 id="questionnaire-title"><?php //echo $this->mode; ?> Online Survey</h3></div>
<hr>
<div class="">
	<h4>Hello <strong>John Doe</strong>. You are being surveyed about SSR / Trade Analyst <strong>Mike Bob</strong> 
	<a class="btn btn-xs btn-default" href="<?php echo $this->url('reporting/site-pages',array('action' => 'contact-us')) ?>" target="_new" data-toggle="modal"><span class="glyphicon glyphicon-flag"></span> Report Error</a> </h4>
    <br>
    <div>
        <!--5. Strongly Agree 4. Agree 3. Neutral 2. Disagree 1. Strongly Disagree  -->
    </div>

</div>

<?php 
foreach ($this->questions as $k => $q ) {
?>
<div class="container">
<div class="row well well-sm question-well <?php echo $k?> not-answered" >
    <div class="col-md-8">
        <span class="badge"><?php echo $k ?> </span> <?php echo $q ?>
    </div>
    <div class="col-md-4">
    <div class="c-answers">
        <label class="radio-inline "><input type="radio" class="answer-radio" name="<?php echo $k ?>" title="Strongly Disagree"> 1 </label>
        <label class="radio-inline "><input type="radio" class="answer-radio" name="<?php echo $k ?>" title="Disagree"> 2 </label>
        <label class="radio-inline "><input type="radio" class="answer-radio" name="<?php echo $k ?>" title="Neutral"> 3 </label>
        <label class="radio-inline "><input type="radio" class="answer-radio" name="<?php echo $k ?>" title="Agree"> 4 </label>
        <label class="radio-inline "><input type="radio" class="answer-radio" name="<?php echo $k ?>" title="Strongly Agree"> 5 </label>
        <label class="radio-inline "><input type="radio" class="answer-radio" name="<?php echo $k ?>"> NA </label>
    </div>
    </div>
</div>
</div>
<?php } ?>

<a id="submit-answer" class="btn btn-primary btn-lg" href="#" onclick="submitAnswer()">Submit Answers</a>

<div class="modal fade report-problem" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Report Error
            </div>
            <div class="modal-body">
                <strong>Please explain error.</strong>
                <textarea class="form-control"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Send</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade select-questionnaire">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Select questionnaire
            </div>
            <div class="modal-body">
                <ul class="list-group">
                <?php
                    foreach ($this->questionnaire as $key => $value) {
                        $url = $this->url('web-survey',array('mode' => $key));
                        echo '<li class="list-group-item"><a href="'.$url.'">'.$value.'</a></li>';
                    }
                ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php
// ====== PARTS  ============
echo $this->confirmIdentity;

 ?>

<script type="text/javascript">
    $(window).load(function(){
        $('.answer-radio').tooltip();
        $('.confirm-identity').modal('show');
        $('.q-explain').popover({
        	trigger: 'focus'
        });
        $('#questionnaire-title').dblclick(function(){
           $('.select-questionnaire').modal('show');
        });
         var debug;
        $('.answer-radio').click(function() {
            $(this).closest('.question-well').removeClass('not-answered');
            $(this).closest('.question-well').removeClass('not-answered-alert');
            console.log($(this).closest('.question-well').attr('class'));
        });      
    });

    function submitAnswer() {
       $('.not-answered').addClass('not-answered-alert');
       if (!$('.question-well').hasClass('not-answered')) {
            $('#submit-answer').attr('href','<?php echo $this->url('web-survey', array('action' => 'thankyou'));?>');
       }  
    }
</script>