<div class="page-title"><h3><?php echo $this->mode; ?> - Online Survey</h3></div>
<div class="well">
	Hello <strong>John Doe</strong>. You are being surveyed about <strong>Mike Bob</strong> part of Lead Generation team. 
	<button class="btn btn-xs btn-default" data-target = '.report-problem' data-toggle="modal"><span class="glyphicon glyphicon-flag"></span> Report Error</button>
</div>

<?php 
foreach ($this->questions as $k => $q ) {
?>
<div class="well c-question">
    <!--<button class="btn btn-default btn-xs q-explain popover-dismiss" data-container="body" data-toggle="popover" data-placement="right" data-content="Some explanation of the question will be here." title="Qustion Explanation">Explain</button>-->
    <strong><?php echo $k ?></strong>
    <?php echo $q ?>
    <div class="c-answers">
	    <input type="radio" name="<?php echo $k ?>"> 5. Strongly Agree <br>
	    <input type="radio" name="<?php echo $k ?>"> 4. Agree <br>
	    <input type="radio" name="<?php echo $k ?>"> 3. Neutral <br>
	    <input type="radio" name="<?php echo $k ?>"> 2. Disagree <br>
	    <input type="radio" name="<?php echo $k ?>"> 1. Strongly Dissagree <br>
	    <input type="radio" name="<?php echo $k ?>"> Not Applicable <br>
	</div>
</div>
<?php } ?>

<a class="btn btn-primary btn-lg" href="<?php echo $this->url('web-survey', array('action' => 'thankyou'));?>">Submit Answers</a>

<div class="modal fade confirm-identity" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Agreement
            </div>
            <div class="modal-body">
                <h4>Thank you for your interest in participating the survey!</h4>
                <br><br>
                Before you can continue with the survey please confirm:
                <ul>
                    <li> I'm <b>John Doe</b> of <b>XXXX</b></li>
                    <li> My answer will reflect the truth as much as possible.</li>
                    <li> More. [TBD]</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">I confirm</button>
                <a href="<?php echo $this->url('web-survey', array('action' => 'refuse')); ?>" class="btn btn-default">I Refuse</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade report-problem" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Report Error
            </div>
            <div class="modal-body">
                <strong>Please explain error.</strong>
                <textarea class="form-control"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Send</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(window).load(function(){
        $('.confirm-identity').modal('show');
        $('.q-explain').popover({
        	trigger: 'focus'
        });
    });
</script>