<div class="page-title"><h3>Online Survey</h3></div>

<div class="well c-question">
    <button class="btn btn-default btn-xs" data-container="body" data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">Explain</button>
    SSR provides high quality market intelligence 
    <?php echo $this->answers;?>
</div>
<div class="well c-question">
    <button class="btn btn-default btn-xs" data-container="body" data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">Explain</button>
    SSR is effective at handling &amp; channeling incoming leads 
    <?php echo $this->answers;?>
</div>
<div class="well c-question">
    <button class="btn btn-default btn-xs" data-container="body" data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">Explain</button>
    SSR is effective at making cold calls to generate leads
    <?php echo $this->answers;?>
</div>

<a class="btn btn-primary btn-lg" href="<?php echo $this->url('web-survey', array('action' => 'thankyou'));?>">Submit Answers</a>

<script type="text/javascript">
    $(window).load(function(){
        $('.confirm-identity').modal('show');
    });
</script>
<div class="modal fade confirm-identity" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Agreement
            </div>
            <div class="modal-body">
                <h4>Thank you for your interest in participating the survey!</h4>
                <br><br>
                Before you can continue with the survey please confirm:
                <ul>
                    <li> I'm <b>John Doe</b> of <b>XXXX</b></li>
                    <li> My answer will reflect the truth as much as possible.</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">I confirm</button>
                <a href="<?php echo $this->url('web-survey', array('action' => 'refuse')); ?>" class="btn btn-default">I Refuse</a>
            </div>
        </div>
    </div>
</div>
