<div class="modal fade confirm-identity" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Introduction
            </div>
            <div class="modal-body">
                <ul>
                    <li>You have been selected to review <strong>Mike Bob</strong></li>
                    <li>If selected in error, please use report button to notify us.</li>
                    <li>You can also click 'remind me later' if you are unable to complete the survey right now.</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Continue to Survey</button>
                <a href="<?php echo $this->url('web-survey', array('action' => 'postpone')) ?>" class="btn btn-default">Remind me Later</a>
                <!-- <a href="<?php echo $this->url('web-survey', array('action' => 'refuse')); ?>" class="btn btn-default">I Refuse</a> -->
            </div>
        </div>
    </div>
</div>