<div class="page-title"><h2><?php echo $this->translate('Close Survey') ?></h2></div>

<div class="row">
	<div class="col-md-12">
	<?php echo $this->tabsMenu ?>
	</div>
</div>
<div class="jumbotron">
	<h5>
		You are about to close the campaign. All unfinished surveys will be disabled.
	</h5>
	<a class="btn btn-danger" href="<?php echo $this->url('reporting/admin-interface',array('action' => 'close-survey-invites')); ?>">
		<?php echo $this->translate('Close Invitations') ?>
	</a>
</div>