<div class="page-title"><h2><?php echo $this->translate('Launch Survey') ?></h2></div>

<div class="row">
	<div class="col-md-12">
	<?php echo $this->tabsMenu ?>
	</div>
</div>
<div class="jumbotron">
	<h5>
		Are you ready to launch the survey?
	</h5>
	<a class="btn btn-primary" href="<?php echo $this->url('reporting/admin-interface',array('action' => 'send-survey-invites')); ?>">
		<?php echo $this->translate('Send Invitations') ?>
	</a>
</div>