<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WebSurvey\Module'                        => __DIR__ . '/Module.php',
    'WebSurvey\Controller\SurveyController' => __DIR__ . '/src/WebSurvey/Controller/SurveyController.php',
    'WebSurveyTest\Framework\TestCase'        => __DIR__ . '/tests/WebSurvey/Framework/TestCase.php',
    'WebSurveyTest\SampleTest'                => __DIR__ . '/tests/WebSurvey/SampleTest.php',
);
