<div class="panel panel-default">
			<table class="table assignments-table">
			<tr>
				<th>Reviewer</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Email</th>
				<th>Country</th>
				<th>Role</th>
				<!--<th>Change to</th>-->
				<th></th>
			</tr>
			<?php foreach ($this->data['reviewers'] as $key => $reviewer) { ?> 
			<tr class="subject-row <?php if($reviewer['status']!='no') echo "success" ?>">
				<td><?php echo $key ?></td>
				<td><?php echo $reviewer['first_name'] ?></td>
				<td><?php echo $reviewer['last_name'] ?></td>
				<td><?php echo $reviewer['email'] ?></td>
				<td><?php echo $reviewer['country'] ?></td>
				<td><?php echo $reviewer['role'] ?></td>
				<td>
					<button class="btn btn-danger btn-xs remove-row">
						<span class="glyphicon glyphicon-remove"></span>
					</button>
				</td>

			</tr>
			<?php } ?>
			<tr id="last-row" class="hidden">

			</tr>
			</table>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
					<select class="form-control">
						<option>Select Reviewer</option>
						<option>Micheal Romance</option>
					</select>
					</div>
					<div class="col-md-6">
						<!--<a class="btn btn-success" aria-hidden="true" href="<?php echo $this->url('reporting/manager-interface', array('action' => 'approve')); ?>">Save</a>
						<a class="btn btn-default">Reject Reviewers</a> --> <button id="add-row" class="btn btn-primary">Add Reviewer</button>
					</div>
				</div>
			</div>
</div>