<div class="panel panel-default">
	<table class="table review-table">
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Role</th>
			<th>Country</th>
			<th></th>
		</tr>
		<tr>
			<td>John</td>
			<td>Doe</td>
			<td>SSR / Trade Analyst</td>
			<td>US</td>
			<td><button class="btn btn-default btn-sm" data-toggle="modal" data-target=".change-reviewer">Show/Approve Reviewers</button></td>
		</tr>
		<tr>
			<td>John</td>
			<td>Doe</td>
			<td>SSR / Trade Analyst</td>
			<td>US</td>
			<td><button class="btn btn-default btn-sm" data-toggle="modal" data-target=".change-reviewer">Show/Approve Reviewers</button></td>
		</tr>
		<tr>
			<td>John</td>
			<td>Doe</td>
			<td>SSR / Trade Analyst</td>
			<td>US</td>
			<td><button class="btn btn-default btn-sm" data-toggle="modal" data-target=".change-reviewer">Show/Approve Reviewers</button></td>
		</tr>
	</table>
</div>
