<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-8">
				<a data-toggle="collapse" href="#filterPanel"
					class="c-filter-toggle"> Show/Hide Filters </a>
			</div>
			<div class="col-md-4">
				<form class="form-inline" role="form">
					<div class="form-group">
						<label><?php echo $this->translate('Period'); ?></label>
						<select class="form-control">
							<option>2014 Cycle 1</option>
							<option>2014 Cycle 2</option>
						</select>
					</div>
				</form>
			</div>
		</div>
		<div class="row panel-collapse collapse in" id="filterPanel">
			<br>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">Rationale
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
						<?php foreach ($this->scorings as $key => $value) { ?>
							<input type="checkbox" checked> <?php echo $key; ?><br> 
						<?php } ?>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">Country
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
						<input type="checkbox" checked> Netherlands <br> <input
							type="checkbox" checked> Japan <br> <input type="checkbox"
							checked> US <br> <input type="checkbox" checked> China <br>
					</div>
				</div>
			</div>
			<!-- <div class="col-md-3">
				<div class="panel panel-default">
					<div class="panel-heading">Suppport Ratio
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
						<input type="checkbox" checked> 5 or more <br> <input
							type="checkbox" checked> 4 <br> <input type="checkbox" checked> 3
						<br> <input type="checkbox" checked> 2 <br> <input type="checkbox"
							checked> 1 <br>
					</div>
				</div>
			</div>  -->
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">ESR
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
					<?php foreach ($this->data as $employees) { ?>
						<input name="SSR" type="checkbox" checked> <?php echo $employees['first_name'].' '.$employees['last_name']; ?><br>
					<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="panel-footer">
		<div class="btn-group">
					<a class="btn btn-primary apply-selection" data-toggle="tooltip" title=""
					href="<?php echo $this->url('reporting/dashboard-interface') ?>">Apply Selection</a>
					<!-- <a class="btn btn-primary compare-selection" data-toggle="tooltip" title="Compare your current selection to previous selection."
					href="<?php echo $this->url('reporting').'?compare=true'?>"
					>Compare Selection</a>
					<button class="btn btn-primary">?</button> -->
				</div>

	</div>
</div>
<script>
	$('.compare-selection').tooltip();
</script>