<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-8">
				<a data-toggle="collapse" href="#filterPanel"
					class="c-filter-toggle"> Show/Hide Filters </a>
			</div>
			<div class="col-md-4">
				<div class="btn-group">
					<a class="btn btn-primary apply-selection" data-toggle="tooltip" title=""
					href="<?php echo $this->url('reporting') ?>">Apply Selection</a>
					<!-- <a class="btn btn-primary compare-selection" data-toggle="tooltip" title="Compare your current selection to previous selection."
					href="<?php echo $this->url('reporting').'?compare=true'?>"
					>Compare Selection</a>
					<button class="btn btn-primary">?</button> -->
				</div>
			</div>
		</div>
		<div class="row panel-collapse collapse out" id="filterPanel">
			<br>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">Key tasks 
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
						<input type="checkbox" checked> Lead Generation <br> <input
							type="checkbox" checked> Agreement Negotiation <br> <input
							type="checkbox" checked> Post-close <br> <input type="checkbox"
							checked> Account Admin <br> <input type="checkbox" checked>
						Internal Admin <br> <input type="checkbox" checked> Sales Planning
						<br>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">Country
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
						<input type="checkbox" checked> Netherlands <br> <input
							type="checkbox" checked> Japan <br> <input type="checkbox"
							checked> US <br> <input type="checkbox" checked> China <br>
					</div>
				</div>
			</div>
			<!-- <div class="col-md-3">
				<div class="panel panel-default">
					<div class="panel-heading">Suppport Ratio
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
						<input type="checkbox" checked> 5 or more <br> <input
							type="checkbox" checked> 4 <br> <input type="checkbox" checked> 3
						<br> <input type="checkbox" checked> 2 <br> <input type="checkbox"
							checked> 1 <br>
					</div>
				</div>
			</div>  -->
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">SSR
					   <button class="btn btn-xs btn-default">All</button>
					   <button class="btn btn-xs btn-default">None</button>
					</div>
					<div class="panel-body c-filter-panel">
						<input name="SSR" type="checkbox" checked> John Doe <br>
						<input name="SSR" type="checkbox" checked> Micheal Jackson <br>
						<input name="SSR" type="checkbox" checked> Jackie Chan <br>
						<input name="SSR" type="checkbox" checked> Emily Lee <br>
						<input name="SSR" type="checkbox" checked> Fredie Mercury <br>
						<input name="SSR" type="checkbox" checked> Helen Troy <br>
						<input name="SSR" type="checkbox" checked> Allan Poe <br>
						<input name="SSR" type="checkbox" checked> Emmet Brown <br>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$('.compare-selection').tooltip();
</script>