<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading"><span class="panel-title">Strength Questions</span></div>
			<div class="panel-body">
				<ol>
					<li>Q1</li>
					<li>Q4</li>
					<li>Q2</li>
				</ol>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading"><span class="panel-title">Opportunity Questions</span></div>
			<div class="panel-body">
				<ol>
					<li>Q3</li>
					<li>Q6</li>
					<li>Q9</li>
				</ol>
			</div>
		</div>
	</div>
</div>