<div class="col-md-4">
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="row">
			<div class="col-md-9">
				<h5><span class="panel-title"><?php echo $this->title; ?></span></h5>
			</div>
			<div class="col-md-3">
				<span class="c-score badge">4.5</span>
			</div>
		</div>
	</div>
	<table class="table">
		<tr>
		  <th></th>
		  <th>Score *</th>
		  <th>Response Rate</th>
		</tr>
		<tr>
			<td>Question 1</td>
			<th>4.4 <span class="label label-warning" data-toggle="tooltip" data-placement="top" title="Too few respondents. Be wary when making decision using this data.">!</span></th>
			<td class="c-score-info-sm">(1 out of 5)</td>
		</tr>
		<tr>
			<td>Question 2</td>
			<th>4.6</th>
			<td class="c-score-info-sm">(4 out of 5)</td>
		</tr>
		<tr>
			<td>Question 3</td>
			<th>4.5</th>
			<td class="c-score-info-sm">(5 out of 5)</td>
		</tr>
	</table>
</div>
</div>