<div class="col-md-4">
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="row">
			<div class="col-md-7">
				<h5><span class="panel-title"><?php echo $this->title; ?></span></h5>
			</div>
			<div class="col-md-5">
				<span class="c-score badge"><?php echo $sa = number_format(rand(3.9,5.0),1)?></span>
				<span class="c-score badge"><?php echo $sb = number_format(rand(3.9,5.0),1)?></span>
			</div>
		</div>
	</div>
	<div class="panel-body c-score-cards">
	<table class="table " >
		<tr>
		  <th>Question</th>
		  <th>Score A</th>
		  <th>Score B</th>
		  <!-- <th>Response Rate</th>  -->
		</tr>
		<?php 
		foreach ($this->questions as $code => $question) {
			$n = rand(1,5);
			$m = rand(1,5);
		?>
		<tr>
			<td class="c-score-info-md"><?php echo $code ?></td>
			<th><?php echo $sa ?>
				<?php if ($n<=2) {?>
				<span class="label label-warning score-warning" data-toggle="tooltip" data-placement="top" title="Too few respondents. Be wary when making decision using this data.">!</span>
				<?php } ?>
			</th>
			<th><?php echo $sb ?>
				<?php if ($m<=2) {?>
				<span class="label label-warning score-warning" data-toggle="tooltip" data-placement="top" title="Too few respondents. Be wary when making decision using this data.">!</span>
				<?php } ?>
			</th>
			<!--  <td class="c-score-info-sm">(<?php echo $n ;?> out of 5)</td>  -->
		</tr>
		<?php } ?>
		<!--  <tr>
			<td>Question 2</td>
			<th>4.6</th>
			<td class="c-score-info-sm">(4 out of 5)</td>
		</tr>
		<tr>
			<td>Question 3</td>
			<th>4.5</th>
			<td class="c-score-info-sm">(5 out of 5)</td>
		</tr> -->
	</table>
	</div>
</div>
</div>
<script>
	$('.score-warning').tooltip();
</script>
