<div class="panel panel-default">
	<div class="panel-heading">
		<span class="panel-title">Survey Results - <strong>SSR / Trade Analyst John Doe</strong></span>
	</div>
	<table class="table table-bordered">
		<tr class="score-table-header">
			<th>Key Task</th>
			<th><?php echo $this->translate('Questions'); ?></th>
			<?php 
				for ($i = 1; $i <= $this->reviewers; $i++)  {
					echo '<th>Rev '.$i.'</th>';
				} 
			?>
			<th class="active">Ave Score</th>
		</tr>
		<?php foreach ($this->scorings as $key => $questions) {
			$first = true; ?>
			<tr>
			<?php if ($first) { $first = false;?>
			
			<th rowspan=<?php echo count($questions) ?>><span class="key-task"><?php echo $key; ?></span></th>
			<?php } else { ?>
			</tr><tr>
			<?php } ?>
			<?php foreach ($questions as $code =>  $question) {?>
			<td>
				<span class="question-text"><?php echo $code.' - '.$question; ?>
				</span>
			</td>
		<?php
			for ($i = 1; $i <= $this->reviewers; $i++)  { ?>
			<td><span class="score-label" title="Double Click to edit">3</span></td>
		<?php } ?>
			<td class="active">3</td>
			</tr>
			<?php } ?>
		<?php } ?>
		<tr>
			<th>Average</th>
			<td></td>
			<?php 
				for ($i = 1; $i <= $this->reviewers; $i++)  {
					echo '<td>3</td>';
				} 
			?>
			<td class="active">3</td>

		</tr>
	</table>
	<div class="panel-footer">
		<a class="btn btn-default" href="<?php echo $this->basePath().'/export/export.xlsx'; ?>"><span class="glyphicon glyphicon-download"></span> Excel Report</a>
	</div>
</div>

<div class="modal fade edit-score-modal" id="scoreModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<span class="modal-title">Change score</span>
			</div>
			<div class="modal-body score-modal-body">
				<form class="form-horizontal">
					<div class="form-group">
						<label class="col-md-4 control-label">Score</label>
						<div class="col-md-2">

							<select class="form-control">
								<?php
									for ($i = 1 ; $i<6; $i++) {
										echo '<option>' . $i .'</option>';
									}
								?>
								<option>NA</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Reason</label>
						<div class="col-md-6">
							<div class="alert alert-danger alert-xs error-message">Reason is required. </div>
							<textarea class="form-control score-reason-control"></textarea>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary update-score-btn">Save</button>
				<button class="btn btn-default" data-dismiss="modal">Cancel</button>
			</div>
		</div>
	</div>
</div>